language: cpp

dist: bionic
addons:
  apt:
    packages:
      binutils-dev
      libiberty-dev

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc # Don't do a gcc build on OSX.

cache: apt

script:
  - mkdir build && cd build && cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug .. && make
  - ./test/tests
